"""
LLM-powered extraction module for luxury watch certificate data.

This module uses Google Gemini with specialized horologist prompting
to extract structured data from noisy OCR text.
"""

import json
import logging
import os
from typing import Optional, Dict, Any
import google.generativeai as genai
from pydantic import ValidationError

from app.models.models import WatchCertificateData, OCRResult

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Expert Horologist Prompt Template
HOROLOGIST_PROMPT_TEMPLATE = """System / Role: You are an expert Horologist and AI Archivist specializing in luxury watch documentation. Your task is to take raw, noisy OCR text extracted from watch certificates, warranty cards, and service receipts, and convert it into a structured, validated JSON object.

Context & Rules:

1. Noise Correction: The input text is generated by an OCR engine (PaddleOCR) and may contain typos (e.g., "Ro1ex" instead of "Rolex", "Subrnarincr" instead of "Submariner"). You must use your domain knowledge of luxury watches to correct these errors.

2. Hallucination Limit: Do not invent data. If a field (like "Serial Number") is not clearly visible or present in the text, return null for that field. Do not guess.

3. Date Normalization: Convert all dates found (purchase date, service date) into YYYY-MM-DD format.

4. Financial Extraction: Identify currency symbols. If multiple prices appear, prioritize the "Total" or "Sold Price".

5. Entity Definition (The Data You Must Find):
   - brand: (String) The manufacturer (e.g., Rolex, Patek Philippe, Omega)
   - model: (String) The specific model name (e.g., Daytona, Nautilus, Speedmaster)
   - reference_number: (String) The alphanumeric model identifier (e.g., 116500LN, 5711/1A). Critical: This often looks like a phone number or mixed code.
   - serial_number: (String) The unique ID of the specific watch
   - document_type: (String) Classify the document type: "Warranty Certificate", "Service Receipt", "Auction Invoice", or "Unknown"
   - date_iso: (String) The primary date on the document (Purchase or Service date) in YYYY-MM-DD format
   - dealer_name: (String) The name of the retailer or jeweler
   - confidence_score: (Float) 0.0 to 1.0 based on text clarity and completeness

Input Text (Raw OCR Output):
\"\"\"
{raw_ocr_text}
\"\"\"

Output Requirement: Return ONLY a valid JSON object. Do not include markdown formatting (like ```json). Do not add conversational text.

JSON Schema:
{{
  "brand": "string or null",
  "model": "string or null",
  "reference_number": "string or null",
  "serial_number": "string or null",
  "document_type": "string",
  "date_iso": "YYYY-MM-DD or null",
  "dealer_name": "string or null",
  "confidence_score": "float (0.0 to 1.0)"
}}"""


class WatchDataExtractor:
    """
    LLM-powered extractor for watch certificate data.
    
    Uses Google Gemini with domain-specific prompting to extract
    structured watch information from noisy OCR text.
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gemini-2.5-flash",
        temperature: float = 0.1
    ):
        """
        Initialize the LLM extractor.
        
        Args:
            api_key: Google API key. If None, reads from GOOGLE_API_KEY env var
            model: Model name (default: gemini-2.5-flash for speed/cost balance)
            temperature: Sampling temperature (lower = more deterministic)
        """
        self.api_key = api_key or os.getenv("GOOGLE_API_KEY")
        
        if not self.api_key:
            raise ValueError(
                "Google API key required. Set GOOGLE_API_KEY environment variable "
                "or pass api_key parameter."
            )
        
        genai.configure(api_key=self.api_key)
        
        # Configure safety settings to be less restrictive for OCR text
        safety_settings = [
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
        ]
        
        self.model = genai.GenerativeModel(
            model_name=model,
            generation_config={
                "temperature": temperature,
                "max_output_tokens": 1000,
            },
            safety_settings=safety_settings
        )
        self.model_name = model
        self.temperature = temperature
        
        logger.info(f"LLM Extractor initialized (model={model}, temperature={temperature})")
    
    def extract_from_ocr(
        self,
        ocr_result: OCRResult,
        max_retries: int = 2
    ) -> WatchCertificateData:
        """
        Extract structured watch data from OCR result.
        
        Args:
            ocr_result: OCRResult object containing raw text
            max_retries: Number of retry attempts if extraction fails
        
        Returns:
            WatchCertificateData with extracted information
        
        Raises:
            ValueError: If extraction fails after retries
        """
        return self.extract_from_text(ocr_result.raw_text, max_retries)
    
    def extract_from_text(
        self,
        raw_text: str,
        max_retries: int = 2
    ) -> WatchCertificateData:
        """
        Extract structured watch data from raw text.
        
        Args:
            raw_text: Raw OCR text or any text containing watch information
            max_retries: Number of retry attempts if extraction fails
        
        Returns:
            WatchCertificateData with extracted information
        
        Raises:
            ValueError: If extraction fails after retries
        """
        if not raw_text or not raw_text.strip():
            logger.warning("Empty or whitespace-only text provided")
            return WatchCertificateData(
                document_type="Unknown",
                confidence_score=0.0
            )
        
        # Keep original for regex fallback
        original_raw_text = raw_text
        
        # Truncate very long text to avoid recitation issues (keep first 800 chars)
        if len(raw_text) > 800:
            logger.info(f"Truncating OCR text from {len(raw_text)} to 800 chars to avoid safety blocks")
            raw_text = raw_text[:800] + "\n...[text truncated]"
        
        # Format prompt with raw OCR text
        prompt = HOROLOGIST_PROMPT_TEMPLATE.format(raw_ocr_text=raw_text)
        
        for attempt in range(max_retries + 1):
            try:
                logger.info(f"LLM extraction attempt {attempt + 1}/{max_retries + 1}")
                
                # Call Gemini API
                response = self.model.generate_content(
                    prompt + "\n\nRespond with ONLY valid JSON, no markdown formatting."
                )
                
                # Check for safety blocking
                if not response.candidates or not response.candidates[0].content.parts:
                    logger.warning(f"Response blocked (finish_reason={response.candidates[0].finish_reason if response.candidates else 'unknown'})")
                    if attempt == max_retries:
                        # Try regex fallback on FULL text (not truncated)
                        logger.warning("Max retries reached with safety blocks, trying regex fallback")
                        try:
                            from regex_extractor import extract_with_regex
                            return extract_with_regex(original_raw_text)
                        except Exception as e:
                            logger.error(f"Regex fallback failed: {e}")
                            return WatchCertificateData(
                                document_type="Unknown",
                                confidence_score=0.3
                            )
                    continue
                
                # Extract JSON from response
                json_text = response.text.strip()
                
                # Remove markdown code blocks if present
                if json_text.startswith("```json"):
                    json_text = json_text.replace("```json", "").replace("```", "").strip()
                elif json_text.startswith("```"):
                    json_text = json_text.replace("```", "").strip()
                
                # Parse and validate
                data_dict = json.loads(json_text)
                watch_data = WatchCertificateData(**data_dict)
                
                logger.info(
                    f"Extraction successful: brand={watch_data.brand}, "
                    f"model={watch_data.model}, confidence={watch_data.confidence_score:.2f}"
                )
                
                return watch_data
                
            except json.JSONDecodeError as e:
                logger.error(f"JSON parsing failed (attempt {attempt + 1}): {str(e)}")
                if attempt == max_retries:
                    raise ValueError(f"Failed to parse LLM response as JSON: {str(e)}") from e
                
            except ValidationError as e:
                logger.error(f"Pydantic validation failed (attempt {attempt + 1}): {str(e)}")
                if attempt == max_retries:
                    raise ValueError(f"LLM output failed validation: {str(e)}") from e
                
            except Exception as e:
                logger.error(f"Unexpected error (attempt {attempt + 1}): {str(e)}")
                if attempt == max_retries:
                    raise ValueError(f"LLM extraction failed: {str(e)}") from e
        
        # Fallback (should not reach here)
        return WatchCertificateData(
            document_type="Unknown",
            confidence_score=0.0
        )
    
    def extract_from_dict(
        self,
        data: Dict[str, Any]
    ) -> WatchCertificateData:
        """
        Create WatchCertificateData from a dictionary (for testing/manual input).
        
        Args:
            data: Dictionary with watch certificate fields
        
        Returns:
            Validated WatchCertificateData instance
        """
        return WatchCertificateData(**data)


def main():
    """Example usage of WatchDataExtractor."""
    import sys
    
    # Example raw OCR text with typical errors
    example_ocr = """
    ROIEX OYSTER PERPETUAl
    Submariner Date
    Ref. 116610LN
    Serial No. Z1234567
    
    WARRANTY CERTIFICATE
    
    Date of Purchase: 15/03/2020
    
    Official Rolex Jeweler
    TOURNEAU
    New York, NY
    
    This watch is guaranteed for 5 years
    """
    
    if len(sys.argv) > 1:
        # Read from file if provided
        with open(sys.argv[1], 'r', encoding='utf-8') as f:
            ocr_text = f.read()
    else:
        ocr_text = example_ocr
    
    try:
        extractor = WatchDataExtractor(model="gemini-1.5-flash")
        result = extractor.extract_from_text(ocr_text)
        
        print("\n" + "="*60)
        print("EXTRACTED WATCH DATA")
        print("="*60)
        print(json.dumps(result.model_dump(), indent=2, ensure_ascii=False))
        print("="*60)
        
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
